version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql_data
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  node: 
    build: 
      context: .
      dockerfile: Dockerfile.node
    container_name: node
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    command: npm run dev

  php:
    build: .
    container_name: php
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment: 
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
    

volumes:
  mysql_data: