version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql_data
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: RealChat
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  php:
    build: .
    container_name: php
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

volumes:
  mysql_data: